@baseUrl = http://localhost:8000/api

### GET request para testar a api
GET {{baseUrl}}/test

###hpost
POST {{baseUrl}}/usuarios/cadastrar
Content-Type: application/json

{
  "nome": "João da Silva",
  "cpf": "02342288140",
  "senha": "Senha@123",
    "idPlano" : 1
}
